### ISSUE TITLE
request: detect phone?

### ISSUE THREAD

**Issue by marc-gist** [jaredwolff/particle-bluetooth-presence-detection#1]
This looks great!  Can it be used to easily detect an Android phone?

**Comment by jaredwolff** [comment]
Hey @marc-gist 

That was my original intention. Unfortunately you'll need a way to enable advertising on your phone. I know for iPhone it would likely require an app. Not sure about Android though. 

If you are able to get it to advertise, you should be good to go.

**Comment by marc-gist** [comment]
Wow, thanks for the quick response!  I'll look into that.
Do you know if there is a way to setup the code (Argon) go accept connections, so that a phone coming close will auto connect to it as a way of detection ? (I'm thinking similar to how when I turn a bluetooth headset on, my phone auto connects to it, so clearly the phone is watching for advertisements?).

**Comment by jaredwolff** [comment]
Hey Marc

I wrote up a post on Particle's Bluetooth API. You should check it out: https://www.jaredwolff.com/how-to-use-particles-powerful-bluetooth-api/

Otherwise Particle's documentation should answer the questions you have here. To summarize a typical connection occurs this way:

- Scan for advertising packets
- Connect
- Do a device discovery
- Confirm you're connected to the right device
- Do any processing with the device now that you're connected
- If not correct, disconnect and then continue scanning.

Hope this helps!
